### ISSUE TITLE
Submit to Lineage team

### ISSUE THREAD

**Issue by ghost** [darran-kelinske-fivestars/android_device_lenovo_tb8504f#4]
Hi darran-kelinske-fivestars,
I would like to inform you that you may want to submit your work to the Lineage developer team.
Here's a guide from them about it: https://wiki.lineageos.org/addingdevice-howto.html
Also I had some difficulties building your repository the TB-8504F ROM (https://github.com/darran-kelinske-fivestars/android_device_lenovo_tb8504f/)for my TB-8504F so I gave up, maybe you should update the README.md to make it more understandable. I understand as this may be overwhelming and as such it's your choice to do whatever you want.
Please respond if you've managed to make and flash this cool ROM of yours.
Another idea is to make a new branch and dedicate to it finished ZIP ROM files that someone like me can flash through TWRP.

P.S. I haven't got a solid grasp of android stuff.

**Comment by dazza5000** [comment]
I never finished the ROM and this was the first one I have ever attempted so there are probably a few things that I did not do correctly.

You're welcome to create a thread on XDA and I will build off that. I have already created quite a few. If you would like to learn and contribute, I will help validate/review your contributions.

**Comment by thegitplant** [comment]
Hi dazza,

I will do my best to start where you left off, from my perspective I think I would finish it in February if not later.
Do you have the binaries of the TB8504F if not it always is a pain in the butt to extract them from the device.

Best regards - PLANT

**Comment by darran-kelinske-fivestars** [comment]
I will see if I can help, but I had to start working on other projects and leave this one behind. Definitely excited to have a possible collaborator. Thank you.

**Comment by thegitplant** [comment]
H1 Darran,
I hope I don't disturb you right now I know you may have some things to do at the moment.
But have you completed the device tree for TB8504F because I think I can create one from:
a) The firmware files from the Russian forums (VERY HARD)
b) The device itself (VERY HARD)
c) Asking for it from Lenovo like other people, BUT THEY NEVER RESPOND! (IMPOSSIBLE)

d) Getting and modifying it from a similar device, but it may be unstable and have bugs (Moderate)

P.S. This email address is a Github one that's redirecting the contents of the mail to your official address, can you give me an email address that is shorter than the current one (reply@...)

**Comment by darran-kelinske-fivestars** [comment]
Do you have a physical TB8504F?

**Comment by thegitplant** [comment]
YES!

**Comment by thegitplant** [comment]
I think this can help but Permissive SElinux is broken

https://forum.xda-developers.com/thinkpad-tablet/development/rom-lineageos-14-1-lenovo-tab4-8-plus-t3948223

**Comment by ghost** [comment]
Well, Yes.

**Comment by thegitplant** [comment]
### Correct me if I'm wrong here
But breakfast doesn't work and therefore you can't brunch. If that's the case I can surely help. But if it isn't well..., I might need more info from you to help with the current work (because **I can't figure  out what you've done so far**). Let me know where a **`problem`** struck and I may be able to dig deeper into it.

**Comment by ghost** [comment]
### Correct me if I'm wrong here
But breakfast doesn't work so far and therefore you can't brunch. If that's the case I can surely help. But if it isn't well..., I might need more info from you to help with the current work (because **I can't figure  out what you've done so far**). Let me know where a **`problem`** struck and I may be able to dig deeper into it.

**Comment by dazza5000** [comment]
This was my first time to try something like this and I don't remember where I got stuck. I was actually able to get it to build locally, but I didn't get all the commits up.

I am starting a new effort from scratch and going to use the kernel from lenovo-devs with a device tree pulled from the device. I started uploading the firmware from the tablet last night here:

https://github.com/dazza5000/android_vendor_lenovo_tb8504f

**Comment by dazza5000** [comment]
I'm going to make a first go at lineage-15.1 because that seems to have the most work for similar devices done. I think actually want to get it ported back to cm-14.1 because that is the API we are using at the company that I am at.

**Comment by ghost** [comment]
Even if I tried my best to help I always get stuck at building because of some stupid error in the code and so I feel like I am useless.
Crossed fingers for your work to pay off. Also you're right about trying to port back to cm-14.1 after building lineage-15.1 as I feel it is most stable.

**Comment by ghost** [comment]
**SOURCE CODE!** 
HI Daran,
I posted some time ago on the lenovo forum a request about requesting source code for the TB-8504F.
Today I got a reply from Adrien_Lenovo with a link to the source code I think you'll like it.

here: https://forums.lenovo.com/t5/Lenovo-Android-based-Tablets-and/RELEASE-ANDROID-SOURCE-CODE-FOR-THE-TB-8504F-AND-TB-8504X/td-p/4575960

**Comment by ghost** [comment]
I need some help syncing my msm8917 repository (here: https://bit.ly/350TYEM)
using roomservice.xml in local_manifests this is what I've got so far: 
```
<?xml version="1.0" encoding="UTF-8"?>
    <manifest>
        <!-- Device Blobs (TX704)-->
        <project name="lenovo-devs/android_device_lenovo_TBX704" path="device/lenovo/TBX704" remote="github" />
        <project name="lenovo-devs/android_device_lenovo_tb-common" path="device/lenovo/tb-common" remote="github" />
        
        <!-- Kernel -->
        <project name="thegitplant/android_kernel_lenovo_msm8917" path="kernel/lenovo/msm8917" remote="github" />

        <!-- Vendor -->
        <project name="lenovo-devs/proprietary_vendor_lenovo" path="vendor/lenovo" remote="github" />
</manifest>
```

what am I doing wrong? (on the cyanogenmod wiki it doesn't say how to set up the path)

**Comment by dazza5000** [comment]
it looks correct - a working manifest example can be found here:

https://github.com/dazza5000/local-manifest-lineage/blob/master/manifest.xml

**Comment by thegitplant** [comment]
thanks but wai a sec

**Comment by ghost** [comment]
Whilst syncing the repo I get this error output:
```
Checking out projects:  95% (673/708) platform/test/vts-testcase/nbuerror: Cannot checkout thegitplant/android_kernel_lenovo_msm8917: ManifestInvalidRevisionError: revision refs/heads/lineage-16.0 in thegitplant/android_kernel_lenovo_msm8917 not found
error: in `sync`: revision refs/heads/lineage-16.0 in thegitplant/android_kernel_lenovo_msm8917 not found
```

**Comment by thegitplant** [comment]
when I do a repo sync

**Comment by ghost** [comment]
Thank you, it looks like you created your own repository of the kernel too, I'll update my roomservice.xml to sync from yours if mine(roomservice.xml) is faulty.

**Comment by dazza5000** [comment]
Sounds good - does your repo work if you add a lineage-16.0 branch?

**Comment by ghost** [comment]
You mean if I would have modified the .xml file to sync from the kernel repository on branch lineage-16 then not really haven't tried it out yet hopefully will after 1h and 30min.

**Comment by ghost** [comment]
If you mean if I did a : repo init -u git://github.com/LineageOS/android.git -b lineage-16.0
than yes I did it worked but haven't tried to build yet, you caught me in the process of using the ./extract-files.sh with adb.

P.S
I will notify you after I attempted building.

**Comment by ghost** [comment]
Can't actually build with this potato PC of mine. I'll need a lot of time to start building.

**Comment by dazza5000** [comment]
You can help me troubleshoot / determine if the device tree is setup
correctly. Do you have a device?

**Comment by dazza5000** [comment]
What is your interest in the TB8504?

**Comment by ghost** [comment]
### It's like this
My interest in the TB8504 is making it better.
I bought it because it was
1. Cheap
2. A challenge to me to make it better.
What I mean by making it better is
1. Rooting | done
2. TWRP | done
3. Magisk mods | done
4. Init.d support + tweaks | done
5. Lineage OS support | in progress
6. Making a custom kernel | haven't started
7. Making it more faster, stabler and power efficient | in progress
and many more things like this you get it.


It's my hobby.


Now HOW may I help you with the device tree.

**Comment by thegitplant** [comment]
Would you like the idea to communicate in Slack. It's better than this. Also:
The kernel you're using android_kernel_lenovo_msm8937 (lenovo-devs's repo) corresponds to Qualcomm Snapdragon 430 (MSM8937), which is not the correct Snapdragon TB8504 has. TB8504 has the Snapdragon 425 (MSM8917) which corresponds to android_kernel_lenovo_msm8917 (my repo). Here's evidence from Lenovo itself: https://support.lenovo.com/cz/en/solutions/pd105086
I recommend  looking at the processor category.

**Comment by ghost** [comment]
However some kernels like msm8917 use some components from others because well they're **similar**, not the same, using a kernel from another device instead of the one wrote for a specific device can lead to unpredictable errors in both booting and usage. Remember that the kernel is the most important piece in ROM building obtaining the trees(vendor+device) is not that hard as making the kernel work.

**Comment by ghost** [comment]
But there's a possibility that they're the same, however I feel like that's unlikely.

**Comment by dazza5000** [comment]
I'd prefer collaborating on xda here: https://forum.xda-developers.com/thinkpad-tablet/development/device-tree-kernel-vendor-tb-8504f-t3934663/page8

**Comment by ghost** [comment]
Yes, thank you see you there.

**Comment by ghost** [comment]
Closed
